workflows:
  build-and-release:
    jobs:
      #--------------- BUILD ---------------#
      - build:
          name: build 2.12.8
          version: 2.12.8
          filters:
            tags:
              only: /^v.*/

      - build:
          name: build 2.13.4
          version: 2.13.4
          filters:
            tags:
              only: /^v.*/

      #--------------- DEPLOY ---------------#
      - release:
          name: release
          requires:
            - build 2.12.8
            - build 2.13.4
          filters:
            tags:
              only: /^v.*/